backend/modules/common/controllers/AttachmentCateController.php
<?php

namespace backend\modules\common\controllers;

use Yii;
use yii\data\ActiveDataProvider;
use common\models\common\AttachmentCate;
use common\enums\AttachmentUploadTypeEnum;
use backend\controllers\BaseController;
use common\traits\MerchantCurd;

/**
 * Class AttachmentCateController
 * @package backend\modules\common\controllers
 * @author jianyan74 <751393839@qq.com>
 */
class AttachmentCateController extends BaseController
{
    use MerchantCurd;

    /**
     * @var AttachmentCate
     */
    public $modelClass = AttachmentCate::class;

    /**
     * Lists all Tree models.
     * @return mixed
     */
    public function actionIndex()
    {
        $type = Yii::$app->request->get('type', AttachmentUploadTypeEnum::IMAGES);

        $dataProvider = new ActiveDataProvider([
            'query' => $this->modelClass::find()
                ->where(['type' => $type])
                ->andWhere([
                    'merchant_id' => Yii::$app->services->merchant->getNotNullId(),
                    'store_id' => Yii::$app->services->store->getNotNullId(),
                ])
                ->orderBy('sort asc, created_at asc'),
            'pagination' => false
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'type' => $type,
        ]);
    }

    /**
     * 编辑/创建
     *
     * @return mixed|string|\yii\web\Response
     * @throws \yii\base\ExitException
     */
    public function actionAjaxEdit()
    {
        $id = Yii::$app->request->get('id', '');
        $type = Yii::$app->request->get('type');
        $model = $this->findModel($id);
        $model->pid = Yii::$app->request->get('pid', null) ?? $model->pid; // 父id

        // ajax 校验
        $this->activeFormValidate($model);
        if ($model->load(Yii::$app->request->post())) {
            $model->type = $type;

            return $model->save()
                ? $this->redirect(['index', 'type' => $type])
                : $this->message($this->getError($model), $this->redirect(['index', 'type' => $type]), 'error');
        }

        return $this->renderAjax('ajax-edit', [
            'model' => $model,
        ]);
    }
}

backend/modules/common/controllers/AttachmentController.php
<?php

namespace backend\modules\common\controllers;

use Yii;
use common\traits\MerchantCurd;
use common\models\base\SearchModel;
use common\models\common\Attachment;
use common\enums\StatusEnum;
use common\enums\AttachmentUploadTypeEnum;
use backend\controllers\BaseController;

/**
 * Class AttachmentController
 * @package backend\modules\common\controllers
 * @author jianyan74 <751393839@qq.com>
 */
class AttachmentController extends BaseController
{
    use MerchantCurd;

    /**
     * @var Attachment
     */
    public $modelClass = Attachment::class;

    /**
     * 首页
     *
     * @return string
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionIndex()
    {
        $type = Yii::$app->request->get('type', AttachmentUploadTypeEnum::IMAGES);

        $searchModel = new SearchModel([
            'model' => $this->modelClass,
            'scenario' => 'default',
            'partialMatchAttributes' => ['title'], // 模糊查询
            'defaultOrder' => [
                'id' => SORT_DESC,
            ],
            'pageSize' => $this->pageSize,
        ]);

        $dataProvider = $searchModel
            ->search(Yii::$app->request->queryParams);
        $dataProvider->query
            ->andWhere(['upload_type' => $type])
            ->andWhere(['>=', 'status', StatusEnum::DISABLED])
            ->andFilterWhere(['merchant_id' => $this->getMerchantId()]);

        return $this->render($this->action->id, [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
            'cateMap' => Yii::$app->services->attachmentCate->getMap($type),
            'type' => $type,
        ]);
    }

    /**
     * @return mixed|string|\yii\web\Response
     * @throws \yii\base\ExitException
     */
    public function actionUpdate()
    {
        $id = Yii::$app->request->get('id');
        $type = Yii::$app->request->get('type');
        $model = $this->findModel($id);

        // ajax 校验
        $this->activeFormValidate($model);
        if ($model->load(Yii::$app->request->post())) {
            return $model->save()
                ? $this->redirect(['index', 'type' => $type])
                : $this->message($this->getError($model), $this->redirect(['index', 'type' => $type]), 'error');
        }

        return $this->renderAjax($this->action->id, [
            'model' => $model,
            'cateMap' => Yii::$app->services->attachmentCate->getMap($type),
        ]);
    }

    /**
     * 返回模型
     *
     * @param $id
     * @return \yii\db\ActiveRecord
     */
    protected function findModel($id)
    {
        /* @var $model \yii\db\ActiveRecord */
        if (
            empty($id) || empty(
                ($model = $this->modelClass::find()
                    ->where(['id' => $id])
                    ->andFilterWhere(['merchant_id' => $this->getMerchantId()])
                    ->one()))
        ) {
            $model = new $this->modelClass;
            return $model->loadDefaultValues();
        }

        return $model;
    }
}

backend/modules/common/views/attachment/index.php
<?php

use yii\grid\GridView;
use yii\helpers\Html as BaseHtml;
use common\helpers\Html;
use common\helpers\ImageHelper;
use common\helpers\DebrisHelper;
use common\helpers\Url;
use common\enums\AttachmentDriveEnum;
use common\enums\AttachmentUploadTypeEnum;

$this->title = '素材管理';
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="row">
    <div class="col-sm-12">
        <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
                <?php foreach (AttachmentUploadTypeEnum::getMap() as $key => $value) { ?>
                    <li class="<?php if ($type == $key) { ?>active<?php } ?>"><a href="<?= Url::to(['attachment/index', 'type' => $key])?>"><?= $value ?></a></li>
                <?php } ?>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active">
                    <div class="tab-pane active">
                        <nav class="nav-tabs-child">
                            <ul>
                                <li class="selected"><a href="<?= Url::to(['attachment/index', 'type' => $type]) ?>">素材文件</a></li>
                                <li><a href="<?= Url::to(['attachment-cate/index', 'type' => $type]) ?>">素材分组</a></li>
                            </ul>
                        </nav>
                        <div class="box">
                            <!-- /.box-header -->
                            <div class="box-body table-responsive">
                                <?= GridView::widget([
                                    'dataProvider' => $dataProvider,
                                    'filterModel' => $searchModel,
                                    // 重新定义分页样式
                                    'tableOptions' => ['class' => 'table table-hover'],
                                    'columns' => [
                                        [
                                            'class' => 'yii\grid\SerialColumn',
                                        ],
                                        [
                                            'attribute' => 'url',
                                            'filter' => false, //不显示搜索框
                                            'value' => function ($model) {
                                                if (($model['upload_type'] == 'images' || preg_match("/^image/", $model['specific_type'])) && $model['extension'] != 'psd') {
                                                    return ImageHelper::fancyBox($model->url);
                                                }

                                                return BaseHtml::a('预览', $model->url, [
                                                    'target' => '_blank'
                                                ]);
                                            },
                                            'format' => 'raw'
                                        ],
                                        [
                                            'attribute' => 'drive',
                                            'headerOptions' => ['class' => 'col-md-1'],
                                            'filter' => Html::activeDropDownList($searchModel, 'drive', AttachmentDriveEnum::getMap(), [
                                                    'prompt' => '全部',
                                                    'class' => 'form-control'
                                                ]
                                            ),
                                            'value' => function ($model) {
                                                return AttachmentDriveEnum::getValue($model->drive);
                                            },
                                        ],
                                        'name',
                                        [
                                            'attribute' => 'format_size',
                                            'filter' => false, //不显示搜索框
                                        ],
                                        [
                                            'attribute' => 'extension',
                                            'headerOptions' => ['class' => 'col-md-1'],
                                        ],
                                        [
                                            'attribute' => 'cate.title',
                                            'label' => '素材分组',
                                            'headerOptions' => ['class' => 'col-md-1'],
                                            'filter' => Html::activeDropDownList($searchModel, 'cate_id', $cateMap, [
                                                    'prompt' => '全部',
                                                    'class' => 'form-control'
                                                ]
                                            ),
                                            'value' => function ($model) {
                                                return $model->cate->title ?? '';
                                            },
                                        ],
                                        [
                                            'label' => '位置信息',
                                            'value' => function ($model) {
                                                $str = [];
                                                $str[] = DebrisHelper::analysisIp($model->ip);
                                                $str[] = $model->ip;
                                                return implode('</br>', $str);
                                            },
                                            'format' => 'raw',
                                        ],
                                        [
                                            'label' => '创建时间',
                                            'attribute' => 'created_at',
                                            'filter' => false, //不显示搜索框
                                            'format' => ['date', 'php:Y-m-d H:i:s'],
                                        ],
                                        [
                                            'header' => "操作",
                                            'class' => 'yii\grid\ActionColumn',
                                            'template' => '{update} {status} {delete}',
                                            'buttons' => [
                                                'update' => function ($url, $model, $key) {
                                                    return Html::linkButton(['update', 'id' => $model->id, 'type' => $model->upload_type], '编辑', [
                                                        'data-toggle' => 'modal',
                                                        'data-target' => '#ajaxModal',
                                                    ]);
                                                },
                                                'status' => function ($url, $model, $key) {
                                                    return Html::status($model->status);
                                                },
                                                'delete' => function ($url, $model, $key) {
                                                    return Html::delete(['destroy', 'id' => $model->id]);
                                                },
                                            ],
                                        ],
                                    ],
                                ]); ?>
                                 <!-- /.box-body -->
                            </div>
                            <!-- /.box -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

backend/modules/common/views/attachment/update.php
<?php

use yii\widgets\ActiveForm;
use common\helpers\Url;
use common\helpers\ArrayHelper;

$form = ActiveForm::begin([
    'id' => $model->formName(),
    'enableAjaxValidation' => true,
    'validationUrl' => Url::to(['update', 'id' => $model['id']]),
    'fieldConfig' => [
        'template' => "<div class='row'><div class='col-sm-2 text-right'>{label}</div><div class='col-sm-10'>{input}\n{hint}\n{error}</div></div>",
    ]
]);
?>

<div class="modal-header">
    <h4 class="modal-title">基本信息</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
</div>
<div class="modal-body">
    <?= $form->field($model, 'name')->textInput(); ?>
    <?= $form->field($model, 'cate_id')->dropDownList(ArrayHelper::merge([0 => '请选择'], $cateMap)); ?>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-white" data-dismiss="modal">关闭</button>
    <button class="btn btn-primary" type="submit">保存</button>
</div>

<?php ActiveForm::end(); ?>